export const ROLES = {
  normal: "normal",
  admin: "admin",
  mantenimiento: "mantenimiento",
  jefeMantenimiento: "jefe-mantenimiento",
  nulo: "nulo",
};

export const SCOPES = {
  canViewDashboard: "can-view-usuario",
  canCreateUsuario: "can-create-usuario",
  canEditUsuario: "can-edit-usuario",
  canDeleteUsuario: "can-delete-usuario",
  canViewUsuario: "can-view-usuario",
  canCreateEquipo: "can-create-equipo",
  canEditEquipo: "can-edit-equipo",
  canDeleteEquipo: "can-delete-equipo",
  canViewEquipo: "can-view-equipo",
  canCreateTicket: "can-create-ticket",
  canEditTicket: "can-edit-ticket",
  canDeleteTicket: "can-delete-ticket",
  canViewTicket: "can-view-ticket",
  canCreateMantenimiento: "can-create-mantenimiento",
  canEditMantenimiento: "can-edit-mantenimiento",
  canDeleteMantenimiento: "can-delete-mantenimiento",
  canViewMantenimiento: "can-view-mantenimiento",
  canViewPerfil: "can-view-perfil",
};

export const PERMISSIONS = {
  [ROLES.normal]: [
    //Solo los propios, chequear en el componente if rol = normal
    SCOPES.canCreateTicket,
    SCOPES.canEditTicket,
    SCOPES.canDeleteTicket,
    SCOPES.canViewTicket,
    SCOPES.canViewPerfil,
  ],
  [ROLES.admin]: [
    SCOPES.canViewDashboard,
    SCOPES.canCreateUsuario,
    SCOPES.canEditUsuario,
    SCOPES.canDeleteUsuario,
    SCOPES.canViewUsuario,
    SCOPES.canCreateEquipo,
    SCOPES.canEditEquipo,
    SCOPES.canDeleteEquipo,
    SCOPES.canViewEquipo,
    SCOPES.canCreateTicket,
    SCOPES.canEditTicket,
    SCOPES.canDeleteTicket,
    SCOPES.canViewTicket,
    SCOPES.canCreateMantenimiento,
    SCOPES.canEditMantenimiento,
    SCOPES.canDeleteMantenimiento,
    SCOPES.canViewMantenimiento,
    SCOPES.canViewPerfil,
  ],
  [ROLES.mantenimiento]: [
    SCOPES.canViewEquipo,
    SCOPES.canCreateTicket,
    SCOPES.canEditTicket,
    SCOPES.canDeleteTicket,
    SCOPES.canViewTicket,
    SCOPES.canEditMantenimiento,
    SCOPES.canViewMantenimiento,
    SCOPES.canViewPerfil,
  ],
  [ROLES.jefeMantenimiento]: [
    SCOPES.canViewDashboard,
    SCOPES.canEditEquipo,
    SCOPES.canDeleteEquipo,
    SCOPES.canViewEquipo,
    SCOPES.canCreateTicket,
    SCOPES.canEditTicket,
    SCOPES.canDeleteTicket,
    SCOPES.canViewTicket,
    SCOPES.canCreateMantenimiento,
    SCOPES.canEditMantenimiento,
    SCOPES.canDeleteMantenimiento,
    SCOPES.canViewMantenimiento,
    SCOPES.canViewPerfil,
  ],
  [ROLES.nulo]: [SCOPES.canViewPerfil],
};
